version: '3.9'

services:
  db:
    image: mongo:latest
    expose:
      - "27017"
    volumes:
      - ./apps/mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=t0ps3cr3t
  proxy:
    image: envoyproxy/envoy:v1.21-latest
    ports:
      - "8080:8080"
      - "9901:9901"
    volumes:
      - ./apps/envoy:/etc/envoy
    depends_on:
      - server
  server:
    build: 
      context: .
    ports:
      - "50051:50051"
    environment:
      - APP_TIMEOUT=10
      - PORT=50051
      - DB_USER=mongouser
      - DB_PASSWORD=t0ps3cr3t
      - DB_HOST=db
    depends_on:
      - db
